###################################################################
#
#  WEB 访问端口号  约定 ： 8081
#
###################################################################
server:
  #port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

###################################################################
#
#  配置数据源信息
#
###################################################################
spring:
  application:
    name: foodie-user-service
  main:
    allow-bean-definition-overriding: true  # 当Bean的名字一样时  允许覆盖
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.103:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  hikari:
    connection-timeout: 30000                   #等待连接池分配连接的最大时长（毫秒）
    minimum-idle:                               #最小连接数
    maximum-pool-size: 20                       #最大连接数
    auto-commit: true                           #自动提交
    idle-timeout: 600000                        #连接超时最大时长（毫秒）
    pool-name: DateSourceHikariCP               #连接池名称
    max-lifetime: 1800000                       #连接的生命时长（毫秒）
    connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  #session:
  #  store-type: redis

###################################################################
#
#  mybatis信息
#
##################################################################
mybatis:
  type-aliases-package: com.imooc.user.pojo
  mapper-locations: classpath:mapper/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

###################################################################
#
#  mapper信息
#
##################################################################
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empry: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
