server:
  port: 10002

spring:
  datasource:
    # 拆分数据源到独立database instance， 或者独立schema
    url: jdbc:mysql://192.168.1.103:3306/foodie-cloud-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    #url: jdbc:mysql://192.168.1.103:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: Passwd123!
  redis:

#    Redis 单机单实例
    database: 1
    host: 192.168.1.131
    port: 6379
    password: 123

#    哨兵模式 1主2从
#    database: 1
#    password: 123
#    sentinel:
#      master: yyf-master
#      nodes: 192.168.1.101:26379,192.168.1.121:26379,192.168.1.131:26379

#    Redis 集群模式 3主从
#    password: 123
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# actuator 暴露接口
management:
  endpoints:
    web:
      exposure:
        # 生产中只需暴露指定端口
        include: "*"
        #include: health, info, xxx

  endpoint:
    health:
      show-details: always

  security:
    enabled: false


## hystrix 策略配置文件形式配置[2]
hystrix:
  command:
    # 默认值
    default:
      fallback: true

    circuitBreaker:
      enabled: true
      ## 请求错误率，高于50% 开启熔断
      errorThresholdPercentage: 50 #生产上配置略低于50%
      ## 请求个数5个以上才进行统计
      requestWindowInMilliseconds: 5
      ## 10s之后进入半开状态
      sleepWindowInMilliseconds: 10000
      ## forceClosed, forceOpen 强制开启/关闭 熔断开关

    execution:
      timeout:
        enabled: true
      ## 可以指定隔离方式是线程池还是信号量
      isolation:
        thread:
          interruptOnTimeout: true
          interruptOnFutureCancel: true
          timeoutInMilliseconds: 4000 # hystrix全局超时时间 注意！！！与 feign 的超时策略相互作用，谁先到达 谁生效

    ## 熔断窗口期
    metrics:
      rollingStats:
        timeInMilliseconds: 20000 # 配置时间窗口
        #numBuckets: 10

#      rollingPercentile:
#        timeInMilliseconds: 20000 # 配置时间窗口
#        #numBuckets: 10
#        bucketSize: 300
    ## 自定义方法级（user-login）别降级策略
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000















