server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://175.24.78.250:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: Passwd123!

  redis:

    #    Redis 单机单实例
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl